# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import Utilidades.funciones_de_test as FDT
import Utilidades.random_email as RE
import Utilidades.random_password as RP
PATH = "C:\Program Files (x86)\chromedriver.exe"
random_user = {}
random_user["email"] = RE.random_email()
random_user["password"] = RP.random_password(8)
random_user["first_name"] = RE.random_string()
random_user["last_name"] = RE.random_string()
random_user["phone"] = RP.random_password_onlydigits(10)
random_user["address1"] = RE.random_string()
random_user["address2"] = RE.random_string()
random_user["city"] = RE.random_string()
random_user["state"] = RE.random_string()
random_user["zip"] = RP.random_password_onlydigits(5)
random_user["country"] = RE.random_string()


class Test_register():
    def setup_method(self):
        self.driver = webdriver.Chrome(PATH)
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test_register(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(2576, 1416)
        self.driver.find_element(By.LINK_TEXT, "Sign In").click()
        self.driver.find_element(By.LINK_TEXT, "Register here").click()
        FDT.input_field(random_user["email"], self.driver, (By.NAME, "email"))
        FDT.input_field(random_user["password"],
                        self.driver, (By.NAME, "password"))
        FDT.input_field(random_user["password"],
                        self.driver, (By.NAME, "cpassword"))
        FDT.input_field(random_user["address1"],
                        self.driver, (By.NAME, "address1"))
        FDT.input_field(random_user["address2"],
                        self.driver, (By.NAME, "address2"))
        FDT.input_field(random_user["city"], self.driver, (By.NAME, "city"))
        FDT.input_field(random_user["state"], self.driver, (By.NAME, "state"))
        FDT.input_field(random_user["zip"], self.driver, (By.NAME, "zipcode"))
        FDT.input_field(random_user["phone"], self.driver, (By.NAME, "phone"))
        FDT.input_field(random_user["first_name"],
                        self.driver, (By.NAME, "firstName"))
        FDT.input_field(random_user["last_name"],
                        self.driver, (By.NAME, "lastName"))
        FDT.input_field(random_user["country"],
                        self.driver, (By.NAME, "country"))
        FDT.click_button(
            self.driver, (By.XPATH, '/html/body/form/p[13]/input'))

    def test_new_login(self):
        FDT.input_field(random_user["email"], self.driver, (By.NAME, "email"))
        FDT.input_field(random_user["password"],
                        self.driver, (By.NAME, "password"))
        FDT.click_button(self.driver, (By.XPATH, '/html/body/form/p[3]/input'))
        user_name = self.driver.find_element(
            By.XPATH, '//*[@id="title"]/div[1]/button').text
        user_name = user_name.split("\n")[1]
        assert user_name == random_user["first_name"]
        action = ActionChains(self.driver)
        action.move_to_element(
            self.driver.find_element(By.XPATH, '//*[@id="title"]/div[1]/button'))
        action.move_to_element(self.driver.find_elements(By.TAG_NAME, "a")[2])
        action.click().perform()
        FDT.click_button(self.driver, (By.LINK_TEXT, "Edit Profile"))
        assert self.driver.find_element(By.NAME, "email").get_attribute(
            "value") == random_user["email"]
        assert self.driver.find_element(By.NAME, "firstName").get_attribute(
            "value") == random_user["first_name"]
        assert self.driver.find_element(By.NAME, "lastName").get_attribute(
            "value") == random_user["last_name"]
        assert self.driver.find_element(By.NAME, "address1").get_attribute(
            "value") == random_user["address1"]
        assert self.driver.find_element(By.NAME, "address2").get_attribute(
            "value") == random_user["address2"]
        assert self.driver.find_element(By.NAME, "city").get_attribute(
            "value") == random_user["city"]
        assert self.driver.find_element(By.NAME, "state").get_attribute(
            "value") == random_user["state"]
        assert self.driver.find_element(By.NAME, "zipcode").get_attribute(
            "value") == random_user["zip"]
        assert self.driver.find_element(By.NAME, "phone").get_attribute(
            "value") == random_user["phone"]
        assert self.driver.find_element(By.NAME, "country").get_attribute(
            "value") == random_user["country"]
        FDT.click_button(
            self.driver, (By.XPATH, '/html/body/div[2]/form/input'))


#-----------Main-----------------#
test = Test_register()
test.setup_method()
test.test_register()
test.test_new_login()
test.teardown_method()
